name: mobile_rs
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_core: ^0.4.5
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.6
  modal_progress_hud: ^0.1.3
  font_awesome_flutter: ^8.8.1
  get_it: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/img/
    - assets/img/skills/
    - assets/img/items/

  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf